"""
This type stub file was generated by pyright.
"""

def unbuildColrV1(layerList, baseGlyphList): # -> dict[Unknown, Unknown]:
    ...

class LayerListUnbuilder:
    def __init__(self, layers) -> None:
        ...
    
    def unbuildPaint(self, paint):
        ...
    


if __name__ == "__main__":
    font = ...
    colr = ...
    colorGlyphs = ...
