"""
This type stub file was generated by pyright.
"""

def buildVarRegionAxis(axisSupport):
    ...

def buildVarRegion(support, axisTags):
    ...

def buildVarRegionList(supports, axisTags): # -> VarRegionList:
    ...

def VarData_calculateNumShorts(self, optimize=...):
    ...

def VarData_CalculateNumShorts(self, optimize=...):
    """Deprecated name for VarData_calculateNumShorts() which
    defaults to optimize=True.  Use varData.calculateNumShorts()
    or varData.optimize()."""
    ...

def VarData_optimize(self):
    ...

def buildVarData(varRegionIndices, items, optimize=...):
    ...

def buildVarStore(varRegionList, varDataList):
    ...

def buildVarIdxMap(varIdxes, glyphOrder): # -> VarIdxMap:
    ...

def buildDeltaSetIndexMap(varIdxes): # -> DeltaSetIndexMap:
    ...

def buildVarDevTable(varIdx):
    ...

