name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
         
      - name: Run Tests
        run: tox
        env:
          python-version: ${{ matrix.python-version }}
